//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTest.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] APPS64_D64 {
            get {
                object obj = ResourceManager.GetObject("APPS64_D64", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Convert_2_5_D64 {
            get {
                object obj = ResourceManager.GetObject("Convert_2_5_D64", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - * CREATES GEOS PROGRAM CONVERT V.25 *QDR²8:FI$²&quot;CONVERT&quot;:TY$²Ç(6):‰18{HI²µ(A­256):˜15,&quot;M-R&quot;Ç(A«HI¬256)Ç(HI)–¡#15,A$:A²Æ(A$ªÇ(0)):Ž¯˜15,&quot;U1:&quot;2;0;TR;SC:ŽÈ
        ///˜15,&quot;U2:&quot;2;0;TR;SC:ŽÝ˜15,&quot;B-P:&quot;2;PS:Žú¡#2,A$:A$²È(A$ªÇ(0),1):Ž	˜2,Ç(A);:Ž8† D$(29):™ &quot;WORKING...&quot;:Ÿ3,DR,3,FI$ª&quot;,U,W&quot;]‡ A$:™ &quot;.&quot;;:‹ A$²&quot;-1&quot; §   3:‰ 30˜ I²1 ¤ Ã(A$):‹ Ê(A$,I,1)²&quot; &quot; § A$²È(A$,I«1)ªÊ(A$,Iª1)Ì‚: I²1 ¤ Ã(A$) © 2:H$²Ê(A$,I,1):L$²Ê(A$,Iª1,1)øH²16¬(Å(H$)«(H$±&quot;@&quot;¯H$³&quot;G&quot;)¬(Æ(H$)«55))/˜3, [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string CONVERT_BAS {
            get {
                return ResourceManager.GetString("CONVERT_BAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] GEOS64_D64 {
            get {
                object obj = ResourceManager.GetObject("GEOS64_D64", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] GEOS64_ZIP {
            get {
                object obj = ResourceManager.GetObject("GEOS64_ZIP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] GPT64_CVT {
            get {
                object obj = ResourceManager.GetObject("GPT64_CVT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] GW64_CVT {
            get {
                object obj = ResourceManager.GetObject("GW64_CVT", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
